# GitHub Action for generating a contribution graph with a snake eating your contributions.
# Original repo: https://github.com/Platane/snk

name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours (30 mins is too frequent, often fails)
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake.gif

      - name: Commit and push if files changed
        run: |
          git config --global user.name "cart00n01"
          git config --global user.email "sanskarsilwal123@gmail.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Generated snake animation"
        continue-on-error: true  # avoids full fail if nothing changed

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

